### ISSUE TITLE
Question: Can you move back to Thorsten's mainline namespace-css?

### ISSUE THREAD

**Issue by chetanddesai** [jeffling/namespace-css-loader#3]
The git ssh reference in your package.json is causing some problems for us at Intuit.  We typically don't have `ssh` ports open and would look to move that to `https` if you need to stay on your fork.

``` json
"namespace-css": "git://github.com/jeffling/namespace-css"
```

Any idea if Thorsten has fixed the bug you found on `namespace-css` that caused you to fork it?  Or have you tried pull-requesting it back?

Cheers!

**Comment by jeffling** [comment]
Hey @chetanddesai , unfortunately he hasn't fixed the bug. There was a PR but he rejected it.  (sorry for replying over a year later). I've merged a PR that may help. 

The bug would have caused all @font-faces and other things to crash, so it would break for most projects.
